In [1]:
# Ecommerce sales analysis project
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv("ecomerce/olist_customers_dataset.csv")
df3=pd.read_csv("ecomerce/olist_order_items_dataset.csv")
df4=pd.read_csv("ecomerce/olist_order_payments_dataset.csv")
df5=pd.read_csv("ecomerce/olist_order_reviews_dataset.csv")
df6=pd.read_csv("ecomerce/olist_orders_dataset.csv")
df7=pd.read_csv("ecomerce/olist_products_dataset.csv")
df8=pd.read_csv("ecomerce/olist_sellers_dataset.csv")
df9=pd.read_csv("ecomerce/product_category_name_translation.csv")

In [3]:
df1.shape

(99441, 5)

In [4]:
df1.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [6]:
df1.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
df1.duplicated().sum()

np.int64(0)

In [8]:
df1.describe(include="all")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [9]:
print(df1.head(5))

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

In [10]:
print(df1.tail())

                            customer_id                customer_unique_id  \
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix    customer_city customer_state
99436                      3937        sao paulo             SP
99437                      6764  taboao da serra             SP
99438                     60115        fortaleza             CE
99439                     92120           canoas             RS
99440                      6703            cotia             SP

In [11]:
df1.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

In [12]:
print(df6.head(5))

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

In [13]:
df6.shape

(99441, 8)

In [14]:
df6.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [15]:
df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [16]:
df6.duplicated().sum()

np.int64(0)

In [17]:
df6.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [18]:
df6.describe(include="all")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [19]:
df6.nunique()

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

In [20]:
date_column=[
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
]
for col in date_column:
    df6[col]=pd.to_datetime(df6[col])

In [21]:
df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [22]:
df6['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [23]:
pd.crosstab(df6['order_status'],df6['order_delivered_customer_date'].isna())

order_delivered_customer_date  False  True
order_status
approved                           0      2
canceled                           6    619
created                            0      5
delivered                      96470      8
invoiced                           0    314
processing                         0    301
shipped                            0   1107
unavailable                        0    609

In [24]:
df6[(df6['order_status']=="delivered")&(df6['order_delivered_customer_date'].isna())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [25]:
df6[
    (
    (df6['order_status']=='delivered')&(df6['order_delivered_customer_date'].isna()))
    ].shape

(8, 8)

In [26]:
df_delivery=df6[
    ~(
    (df6['order_status']=='delivered')&(df6['order_delivered_customer_date'].isna()))
    ].copy()

In [27]:
type(df_delivery)

pandas.DataFrame

In [28]:
df_delivery['actual_delivery_days']=(df_delivery['order_delivered_customer_date'] - df_delivery['order_purchase_timestamp']).dt.days

In [29]:
df_delivery[['order_purchase_timestamp','order_delivered_customer_date','actual_delivery_days']].head()

  order_purchase_timestamp order_delivered_customer_date  actual_delivery_days
0      2017-10-02 10:56:33           2017-10-10 21:25:13                   8.0
1      2018-07-24 20:41:37           2018-08-07 15:27:45                  13.0
2      2018-08-08 08:38:49           2018-08-17 18:06:29                   9.0
3      2017-11-18 19:28:06           2017-12-02 00:28:42                  13.0
4      2018-02-13 21:18:39           2018-02-16 18:17:02                   2.0

In [30]:
df_delivery['actual_delivery_days'].describe()

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: actual_delivery_days, dtype: float64

In [31]:
df_delivery['delay_days']=(df_delivery['order_delivered_customer_date']-df_delivery['order_estimated_delivery_date']).dt.days

In [32]:
df_delivery[['delay_days','order_delivered_customer_date','order_estimated_delivery_date']].head()

   delay_days order_delivered_customer_date order_estimated_delivery_date
0        -8.0           2017-10-10 21:25:13                    2017-10-18
1        -6.0           2018-08-07 15:27:45                    2018-08-13
2       -18.0           2018-08-17 18:06:29                    2018-09-04
3       -13.0           2017-12-02 00:28:42                    2017-12-15
4       -10.0           2018-02-16 18:17:02                    2018-02-26

In [33]:
df_delivery['delay_days'].describe()

count    96476.000000
mean       -11.876881
std         10.183854
min       -147.000000
25%        -17.000000
50%        -12.000000
75%         -7.000000
max        188.000000
Name: delay_days, dtype: float64

In [34]:
df_delivery['delay_days'].apply(lambda x:'delay' if x>0 else('ontime' if x==0 else 'early')).value_counts()

delay_days
early     91606
delay      6535
ontime     1292
Name: count, dtype: int64

In [35]:
df_delivery[df_delivery['delay_days']>0]['delay_days'].describe()

count    6535.000000
mean       10.620352
std        14.643844
min         1.000000
25%         3.000000
50%         7.000000
75%        13.000000
max       188.000000
Name: delay_days, dtype: float64

In [36]:
df_delivery.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'actual_delivery_days', 'delay_days'],
      dtype='str')

In [37]:
df_delivery['delivery_performance']=df_delivery['delay_days'].apply(lambda x:'delay' if x>0 else('ontime' if x==0 else 'early'))

In [38]:
df_delivery['delivery_performance'].value_counts()

delivery_performance
early     91606
delay      6535
ontime     1292
Name: count, dtype: int64

In [39]:
df_delivery['order_month']=(df_delivery['order_purchase_timestamp'].dt.to_period('M'))
df_delivery['order_month'].value_counts().sort_index()

order_month
2016-09       4
2016-10     324
2016-12       1
2017-01     800
2017-02    1780
2017-03    2682
2017-04    2404
2017-05    3699
2017-06    3245
2017-07    4026
2017-08    4331
2017-09    4285
2017-10    4631
2017-11    7543
2017-12    5673
2018-01    7269
2018-02    6728
2018-03    7211
2018-04    6939
2018-05    6873
2018-06    6164
2018-07    6289
2018-08    6512
2018-09      16
2018-10       4
Freq: M, Name: count, dtype: int64

In [40]:
df6.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [41]:
print(df7.head(5))

                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

In [42]:
print(df8.head(5))

                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

In [43]:
print(df9.head(5))

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [44]:
df3.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [45]:
df3.tail()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [46]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [47]:
df3.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [48]:
df3.nunique()

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

In [49]:
df3.duplicated().sum()

np.int64(0)

In [50]:
df3['shipping_limit_date']=pd.to_datetime(df3['shipping_limit_date'])

In [51]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [52]:
df3[['price','freight_value']].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [53]:
df3[df3['price']==df3['price'].max()]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:36,6735.0,194.31

In [54]:
df3[df3['freight_value']==df3['freight_value'].max()]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
73486,a77e1550db865202c56b19ddc6dc4d53,1,ec31d2a17b299511e7c8627be9337b9b,257e61d3251fb5efb9daadddbc2cf7ca,2018-04-25 06:55:13,979.0,409.68

In [55]:
df4.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [56]:
df4.tail()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [57]:
df4.duplicated().sum()

np.int64(0)

In [58]:
df4.nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [59]:
df4.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [60]:
df4.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [61]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [62]:
df4.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [63]:
df4.shape

(103886, 5)

In [64]:
df4[df4['payment_installments']==0].shape

(2, 5)

In [65]:
df4[df4['payment_installments']==0]['payment_type'].value_counts()

payment_type
credit_card    2
Name: count, dtype: int64

In [66]:
df4[df4['payment_installments']==0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [67]:
df5.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [68]:
df5.tail()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [69]:
df5.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [70]:
df5.duplicated().sum()

np.int64(0)

In [71]:
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [72]:
df5['review_creation_date']=pd.to_datetime(df5['review_creation_date'])
df5['review_answer_timestamp']=pd.to_datetime(df5['review_answer_timestamp'])

In [73]:
df5['review_creation_date'].info()

<class 'pandas.Series'>
RangeIndex: 99224 entries, 0 to 99223
Series name: review_creation_date
Non-Null Count  Dtype
--------------  -----
99224 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 775.3 KB

In [74]:
df5['review_answer_timestamp'].info()

<class 'pandas.Series'>
RangeIndex: 99224 entries, 0 to 99223
Series name: review_answer_timestamp
Non-Null Count  Dtype
--------------  -----
99224 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 775.3 KB

In [75]:
(df5['review_answer_timestamp']<df5['review_creation_date']).sum()

np.int64(0)

In [76]:
df5.shape

(99224, 7)

In [77]:
df5.describe()

       review_score        review_creation_date     review_answer_timestamp
count  99224.000000                       99224                       99224
mean       4.086421  2018-01-12 20:49:23.948238  2018-01-16 00:23:56.977939
min        1.000000         2016-10-02 00:00:00         2016-10-07 18:32:28
25%        4.000000         2017-09-23 00:00:00  2017-09-27 01:53:27.250000
50%        5.000000         2018-02-02 00:00:00  2018-02-04 22:41:47.500000
75%        5.000000         2018-05-16 00:00:00  2018-05-20 12:11:21.500000
max        5.000000         2018-08-31 00:00:00         2018-10-29 12:27:35
std        1.347579                         NaN                         NaN

In [78]:
df5['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [79]:
df5['review_comment_title']=df5['review_comment_title'].fillna('no comment')
df5['review_comment_message']=df5['review_comment_message'].fillna('no comment')

In [80]:
df5[['review_comment_title','review_comment_message']].isna().sum()

review_comment_title      0
review_comment_message    0
dtype: int64

In [81]:
df7.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [82]:
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [83]:
df7.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [84]:
df7.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [85]:
df7['product_category_name']=df7['product_category_name'].fillna('unknown')
df7['product_name_lenght']=df7['product_name_lenght'].fillna(0)
df7['product_description_lenght']=df7['product_description_lenght'].fillna(0)
df7['product_photos_qty']=df7['product_photos_qty'].fillna(0)

In [86]:
physical_columns=[
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]
for col in physical_columns:
    df7[col]=df7[col].fillna(df7[col].median())

In [87]:
df7[physical_columns].isna().sum()

product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

In [88]:
df7.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [89]:
df8.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [90]:
df8.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [91]:
df8.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [92]:
df8.duplicated().sum()

np.int64(0)

In [93]:
df9.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [94]:
df9.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [95]:
df9.duplicated().sum()

np.int64(0)

In [96]:
df9.describe()

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [97]:
for name,df in {
    'df1':df1,
    'df3':df3,
    'df4':df4,
    'df5':df5,
    'df6':df6,
    'df7':df7,
    'df8':df8,
    'df9':df9,
}.items():
    print(name,list(df.columns))

df1 ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
df3 ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
df4 ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
df5 ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
df6 ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
df7 ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
df8 ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
df9 ['product_category_name', 'product_category_name_english']

In [98]:
df_main=df6.merge(df3 , on='order_id',how='left')

In [99]:
df_main.shape

(113425, 14)

In [100]:
df_main.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [101]:
df_main.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 14 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  datetime64[us]
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
dtypes: datetime64[us](6), float64(3), str(5)
memory usage: 12.1 MB

In [102]:
df_main=df_main.merge(df1,on='customer_id',how='left')

In [103]:
df_main.shape

(113425, 18)

In [104]:
df_main.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  datetime64[us]
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
 14  customer_unique_id             113425 non-null  str
 15  customer_zip_code_prefix       113425 non-null  int64
 16  customer_city                  113425 non-null  str
 17  customer_state                 113425 non-null  str
dtypes: datetime64[us](6), float64(3), int64(1), str(8)
memory usage: 15.6 MB

In [105]:
df_main=df_main.merge(df7,on='product_id',how='left')

In [106]:
df_main.shape

(113425, 26)

In [107]:
df_main.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [108]:
df_main.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  datetime64[us]
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
 14  customer_unique_id             113425 non-null  str
 15  customer_zip_code_prefix       113425 non-null  int64
 16  customer_city                  113425 non-null  str
 17  customer_state                 113425 non-null  str
 18  product_category_name          112650 non-null  str
 19  product_name_lenght            112650 non-null  float64
 20  product_description_lenght     112650 non-null  float64
 21  product_photos_qty             112650 non-null  float64
 22  product_weight_g               112650 non-null  float64
 23  product_length_cm              112650 non-null  float64
 24  product_height_cm              112650 non-null  float64
 25  product_width_cm               112650 non-null  float64
dtypes: datetime64[us](6), float64(10), int64(1), str(9)
memory usage: 22.5 MB

In [109]:
df_main=df_main.merge(df8,on='seller_id',how='left')

In [110]:
df_main.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  datetime64[us]
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
 14  customer_unique_id             113425 non-null  str
 15  customer_zip_code_prefix       113425 non-null  int64
 16  customer_city                  113425 non-null  str
 17  customer_state                 113425 non-null  str
 18  product_category_name          112650 non-null  str
 19  product_name_lenght            112650 non-null  float64
 20  product_description_lenght     112650 non-null  float64
 21  product_photos_qty             112650 non-null  float64
 22  product_weight_g               112650 non-null  float64
 23  product_length_cm              112650 non-null  float64
 24  product_height_cm              112650 non-null  float64
 25  product_width_cm               112650 non-null  float64
 26  seller_zip_code_prefix         112650 non-null  float64
 27  seller_city                    112650 non-null  str
 28  seller_state                   112650 non-null  str
dtypes: datetime64[us](6), float64(11), int64(1), str(11)
memory usage: 25.1 MB

In [111]:
df_main.shape

(113425, 29)

In [112]:
df_main=df_main.merge(df9,on='product_category_name',how='left')

In [113]:
df_main.shape

(113425, 30)

In [114]:
df_main.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1968
order_delivered_customer_date    3229
order_estimated_delivery_date       0
order_item_id                     775
product_id                        775
seller_id                         775
shipping_limit_date               775
price                             775
freight_value                     775
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_category_name             775
product_name_lenght               775
product_description_lenght        775
product_photos_qty                775
product_weight_g                  775
product_length_cm                 775
product_height_cm                 775
product_width_cm                  775
seller_zip_code_prefix            775
seller_city                       775
seller_state                      775
product_category_name_english    2402
dtype: int64

In [115]:
df_main[df_main['product_id'].isna()]['order_status'].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [116]:
df_main=df_main.dropna(subset=['product_id'])

In [117]:
df_main.shape

(112650, 30)

In [118]:
df_main.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_category_name               0
product_name_lenght                 0
product_description_lenght          0
product_photos_qty                  0
product_weight_g                    0
product_length_cm                   0
product_height_cm                   0
product_width_cm                    0
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
product_category_name_english    1627
dtype: int64

In [119]:
df_main[df_main['order_approved_at'].isna()]['order_status'].value_counts()

order_status
delivered    15
Name: count, dtype: int64

In [120]:
df_main[df_main['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
canceled       466
invoiced       359
processing     357
unavailable      7
approved         3
delivered        2
Name: count, dtype: int64

In [121]:
df_main[(df_main['order_status']=='delivered')&(df_main['order_delivered_carrier_date'].isna())][['order_id','order_purchase_timestamp','order_delivered_carrier_date','order_approved_at','order_delivered_customer_date','order_estimated_delivery_date']]

,order_id,order_purchase_timestamp,order_delivered_carrier_date,order_approved_at,order_delivered_customer_date,order_estimated_delivery_date
83453,2aa91108853cecb43c84a5dc5b277475,2017-09-29 08:52:58,NaT,2017-09-29 09:07:16,2017-11-20 19:44:47,2017-11-14
105606,2d858f451373b04fb5c984a1cc2defaf,2017-05-25 23:22:43,NaT,2017-05-25 23:30:16,NaT,2017-06-23

In [122]:
df_main[df_main['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1185
canceled        535
invoiced        359
processing      357
delivered         8
unavailable       7
approved          3
Name: count, dtype: int64

In [123]:
df_main[(df_main['order_status']=='delivered')&(df_main['order_delivered_customer_date'].isna())][['order_id','order_purchase_timestamp','order_delivered_carrier_date','order_approved_at','order_delivered_customer_date','order_estimated_delivery_date']]

,order_id,order_purchase_timestamp,order_delivered_carrier_date,order_approved_at,order_delivered_customer_date,order_estimated_delivery_date
3376,2d1e2d5bf4dc7227b3bfebb81328c15f,2017-11-28 17:44:07,2017-11-30 18:12:23,2017-11-28 17:56:40,NaT,2017-12-18
23485,f5dd62b788049ad9fc0526e3ad11a097,2018-06-20 06:58:43,2018-06-25 08:05:00,2018-06-20 07:19:05,NaT,2018-07-16
49966,2ebdfc4f15f23b91474edf87475f108e,2018-07-01 17:05:11,2018-07-03 13:57:00,2018-07-01 17:15:12,NaT,2018-07-30
90294,e69f75a717d64fc5ecdfae42b2e8e086,2018-07-01 22:05:55,2018-07-03 13:57:00,2018-07-01 22:15:14,NaT,2018-07-30
94388,0d3268bad9b086af767785e3f0fc0133,2018-07-01 21:14:02,2018-07-03 09:28:00,2018-07-01 21:29:54,NaT,2018-07-24
105606,2d858f451373b04fb5c984a1cc2defaf,2017-05-25 23:22:43,NaT,2017-05-25 23:30:16,NaT,2017-06-23
111339,ab7c89dc1bf4a1ead9d6ec1ec8968a84,2018-06-08 12:09:39,2018-06-12 14:10:00,2018-06-08 12:36:39,NaT,2018-06-26
111783,20edc82cf5400ce95e1afacc25798b31,2018-06-27 16:09:12,2018-07-03 19:26:00,2018-06-27 16:29:30,NaT,2018-07-19

In [124]:
df_main[df_main['product_category_name_english'].isna()]['product_category_name'].isna().sum()

np.int64(0)

In [125]:
df9[df9['product_category_name'].isin(
    df_main.loc[df_main['product_category_name_english'].isna(),'product_category_name']
)].head(10)

Empty DataFrame
Columns: [product_category_name, product_category_name_english]
Index: []

In [126]:
df_main.loc[df_main['product_category_name_english'].isna(),['product_category_name','product_category_name_english']].head(20)

,product_category_name,product_category_name_english
6,unknown,NaN
122,unknown,NaN
212,unknown,NaN
264,unknown,NaN
303,unknown,NaN
376,unknown,NaN
530,unknown,NaN
587,unknown,NaN
776,unknown,NaN
806,unknown,NaN
1045,portateis_cozinha_e_preparadores_de_alimentos,NaN
1110,unknown,NaN
1365,unknown,NaN
1378,unknown,NaN
1511,unknown,NaN
1649,unknown,NaN
1712,unknown,NaN
1807,unknown,NaN
1834,unknown,NaN
1923,unknown,NaN

In [127]:
df_main.loc[df_main['product_category_name_english'].isna(),'product_category_name'].value_counts(dropna='false').head(20)

product_category_name
unknown                                          1603
portateis_cozinha_e_preparadores_de_alimentos      15
pc_gamer                                            9
Name: count, dtype: int64

In [128]:
df_main['product_category_name_english']=df_main['product_category_name_english'].fillna('unknown')

In [129]:
df_main['product_category_name_english'].isna().sum()

np.int64(0)

In [130]:
df_main.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_category_name               0
product_name_lenght                 0
product_description_lenght          0
product_photos_qty                  0
product_weight_g                    0
product_length_cm                   0
product_height_cm                   0
product_width_cm                    0
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
product_category_name_english       0
dtype: int64

In [131]:
df_main['actual_delivery_days']=(df_main['order_delivered_customer_date']-df_main['order_purchase_timestamp']).dt.total_seconds()/(24*60*60)

In [132]:
df_main['delay_days']=(df_main['order_delivered_customer_date']-df_main['order_estimated_delivery_date']).dt.days

In [133]:
df_main[['order_id','order_purchase_timestamp','order_delivered_customer_date','order_estimated_delivery_date','delay_days','actual_delivery_days']].head(20)

,order_id,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,delay_days,actual_delivery_days
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,-8.0,8.436574
1,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,-6.0,13.782037
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,-18.0,9.394213
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,-13.0,13.208750
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,-10.0,2.873877
5,a4591c265e18cb1dcee52889e2d8acc3,2017-07-09 21:57:05,2017-07-26 10:57:55,2017-08-01,-6.0,16.542245
6,136cce7faa42fdb2cefd53fdc79a6098,2017-04-11 12:22:08,NaT,2017-05-09,NaN,NaN
7,6514b8ad8028c9f2cc2374ded245783f,2017-05-16 13:10:30,2017-05-26 12:55:51,2017-06-07,-12.0,9.989826
8,76c6e866289321a7c93b82b54852dc33,2017-01-23 18:29:09,2017-02-02 14:08:10,2017-03-06,-32.0,9.818762
9,e69bfb5eb88e0ed6a785585b27e16dbf,2017-07-29 11:55:02,2017-08-16 17:14:30,2017-08-23,-7.0,18.221852
10,e6ce16cb79ec1d90b1da9085a6118aeb,2017-05-16 19:41:10,2017-05-29 11:18:31,2017-06-07,-9.0,12.650937
11,e6ce16cb79ec1d90b1da9085a6118aeb,2017-05-16 19:41:10,2017-05-29 11:18:31,2017-06-07,-9.0,12.650937
12,34513ce0c4fab462a55830c0989c7edb,2017-07-13 19:58:11,2017-07-19 14:04:48,2017-08-08,-20.0,5.754595
13,82566a660a982b15fb86e904c8d32918,2018-06-07 10:06:19,2018-06-19 12:05:52,2018-07-18,-29.0,12.083021
14,5ff96c15d0b717ac6ad1f3d77225a350,2018-07-25 17:44:10,2018-07-30 15:52:25,2018-08-08,-9.0,4.922396
15,432aaf21d85167c2c86ec9448c4e42cc,2018-03-01 14:14:28,2018-03-12 23:36:26,2018-03-21,-9.0,11.390255
16,dcb36b511fcac050b97cd5c05de84dc3,2018-06-07 19:03:12,2018-06-21 15:34:32,2018-07-04,-13.0,13.855093
17,403b97836b0c04a622354cf531062e5f,2018-01-02 19:00:43,2018-01-20 01:38:59,2018-02-06,-17.0,17.276574
18,116f0b09343b49556bbad5f35bee0cdf,2017-12-26 23:41:31,2018-01-08 22:36:36,2018-01-29,-21.0,12.954919
19,85ce859fd6dc634de8d2f1e290444043,2017-11-21 00:03:41,2017-11-27 18:28:00,2017-12-11,-14.0,6.766887

In [134]:
df_main['delivery_status']=np.select([
    df_main['delay_days']>0,
    df_main['delay_days']==0,
    df_main['delay_days']<0,
],['delay','ontime','early'],default='notdelivered')

In [135]:
df_main[['delay_days','delivery_status']].head()

   delay_days delivery_status
0        -8.0           early
1        -6.0           early
2       -18.0           early
3       -13.0           early
4       -10.0           early

In [136]:
df_main['delivery_status'].value_counts()

delivery_status
early           101481
delay             7265
notdelivered      2454
ontime            1450
Name: count, dtype: int64

In [137]:
df_main.groupby('delivery_status')['delay_days'].agg(['min','max','mean','count'])

                   min    max       mean   count
delivery_status
delay              1.0  188.0  10.488782    7265
early           -147.0   -1.0 -13.814221  101481
notdelivered       NaN    NaN        NaN       0
ontime             0.0    0.0   0.000000    1450

In [138]:
df_main['order_month']=df_main['order_purchase_timestamp'].dt.to_period('M')

In [139]:
df_main['order_month'].head()

0    2017-10
1    2018-07
2    2018-08
3    2017-11
4    2018-02
Name: order_month, dtype: period[M]

In [140]:
monthly_order=df_main.groupby('order_month')['order_id'].nunique()
monthly_order

order_month
2016-09       3
2016-10     308
2016-12       1
2017-01     789
2017-02    1733
2017-03    2641
2017-04    2391
2017-05    3660
2017-06    3217
2017-07    3969
2017-08    4293
2017-09    4243
2017-10    4568
2017-11    7451
2017-12    5624
2018-01    7220
2018-02    6694
2018-03    7188
2018-04    6934
2018-05    6853
2018-06    6160
2018-07    6273
2018-08    6452
2018-09       1
Freq: M, Name: order_id, dtype: int64

In [141]:
monthly_sales=df_main.groupby('order_month')['price'].sum()

In [142]:
monthly_sales

order_month
2016-09        267.36
2016-10      49507.66
2016-12         10.90
2017-01     120312.87
2017-02     247303.02
2017-03     374344.30
2017-04     359927.23
2017-05     506071.14
2017-06     433038.60
2017-07     498031.48
2017-08     573971.68
2017-09     624401.69
2017-10     664219.43
2017-11    1010271.37
2017-12     743914.17
2018-01     950030.36
2018-02     844178.71
2018-03     983213.44
2018-04     996647.75
2018-05     996517.68
2018-06     865124.31
2018-07     895507.22
2018-08     854686.33
2018-09        145.00
Freq: M, Name: price, dtype: float64

In [143]:
category_sales=(df_main.groupby('product_category_name_english')['price'].sum().sort_values(ascending=False))

In [144]:
category_sales.head(10)

product_category_name_english
health_beauty            1258681.34
watches_gifts            1205005.68
bed_bath_table           1036988.68
sports_leisure            988048.97
computers_accessories     911954.32
furniture_decor           729762.49
cool_stuff                635290.85
housewares                632248.66
auto                      592720.11
garden_tools              485256.46
Name: price, dtype: float64

In [145]:
category_order=(df_main.groupby('product_category_name_english')['order_id'].nunique().sort_values(ascending=False))

In [146]:
category_order.head(10)

product_category_name_english
bed_bath_table           9417
health_beauty            8836
sports_leisure           7720
computers_accessories    6689
furniture_decor          6449
housewares               5884
watches_gifts            5624
telephony                4199
auto                     3897
toys                     3886
Name: order_id, dtype: int64

In [147]:
category_aov=category_sales/category_order

In [148]:
category_aov.sort_values(ascending=False).head(10)

product_category_name_english
computers                                1231.840497
small_appliances_home_oven_and_coffee     632.609467
home_appliances_2                         484.263846
agro_industry_and_commerce                398.519066
musical_instruments                       304.934522
small_appliances                          302.616794
fixed_telephony                           274.576037
construction_tools_safety                 242.781557
air_conditioning                          217.489960
office_furniture                          215.208720
dtype: float64

In [149]:
payment_order=(df4.groupby('payment_type')['order_id'].nunique()).sort_values(ascending=False)

In [150]:
payment_order

payment_type
credit_card    76505
boleto         19784
voucher         3866
debit_card      1528
not_defined        3
Name: order_id, dtype: int64

In [151]:
df4.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [152]:
payment_value=(df4.groupby('payment_type')['payment_value'].sum().sort_values(ascending=False))

In [153]:
payment_value

payment_type
credit_card    12542084.19
boleto          2869361.27
voucher          379436.87
debit_card       217989.79
not_defined           0.00
Name: payment_value, dtype: float64

In [154]:
payment_aov=payment_value/payment_order

In [155]:
payment_aov.sort_values(ascending=False)

payment_type
credit_card    163.938098
boleto         145.034435
debit_card     142.663475
voucher         98.147147
not_defined      0.000000
dtype: float64

In [156]:
installment_counts=(df4.groupby('payment_installments')['order_id'].nunique().sort_index())

In [157]:
installment_counts

payment_installments
0         2
1     49060
2     12389
3     10443
4      7088
5      5234
6      3916
7      1623
8      4253
9       644
10     5315
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: order_id, dtype: int64

In [158]:
total_customers=df_main['customer_unique_id'].nunique()

In [159]:
total_customers

95420

In [160]:
customer_orders=(df_main.groupby('customer_unique_id')['order_id'].nunique())
customer_orders.head(10)

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
0004bd2a26a76fe21f786e4fbd80607f    1
00050ab1314c0e55a6ca13cf7181fecf    1
00053a61a98854899e70ed204dd4bafe    1
0005e1862207bf6ccc02e4228effd9a0    1
0005ef4cd20d2893f0d9fbd94d3c0d97    1
Name: order_id, dtype: int64

In [161]:
customer_orders.mean()

np.float64(1.034018025571159)

In [162]:
one_time_customer=(customer_orders==1).sum()

In [163]:
one_time_customer

np.int64(92507)

In [164]:
repeat_customer=(customer_orders>1).sum()

In [165]:
repeat_customer

np.int64(2913)

In [166]:
repeat_customer_percentage=(repeat_customer/total_customers*100)

In [167]:
repeat_customer_percentage

np.float64(3.0528191154894153)

In [168]:
one_time_customer_percentage=(one_time_customer/total_customers*100)

In [169]:
one_time_customer_percentage

np.float64(96.94718088451059)

In [170]:
customer_orders.value_counts().sort_index()

order_id
1     92507
2      2673
3       192
4        29
5         9
6         5
7         3
9         1
16        1
Name: count, dtype: int64

In [171]:
customer_sales=(df_main.groupby('customer_unique_id')['price'].sum())
customer_sales.sort_values(ascending=False).head(10)

customer_unique_id
0a0a92112bd4c708ca5fde585afaa872    13440.0
da122df9eeddfedc1dc1f5349a1a690c     7388.0
763c8b1c9c68a0229c42c9fc6f662b93     7160.0
dc4802a71eae9be1dd28f5d788ceb526     6735.0
459bef486812aa25204be022145caa62     6729.0
ff4159b92c40ebe40454e3e6a7c35ed6     6499.0
4007669dec559734d6f53e029e360987     5934.6
eebb5dda148d3893cdaf5b5ca3040ccb     4690.0
5d0a2980b292d049061542014e8960bf     4599.9
48e1ac109decbb87765a3eade6854098     4590.0
Name: price, dtype: float64

In [172]:
customer_type=customer_orders.apply(
    lambda x:  'one_time' if x==1 else 'repeat'
)

In [173]:
customer_type.sort_values(ascending=False).head(10)

customer_unique_id
81b133c3f4e30a14a6585a2f20ff150f    repeat
b64064e3ae051f50b6f1eb12552d30e4    repeat
8ba03ea7a871bdaebd65e7a4ced27c2d    repeat
e559969619d1a0922477a2d8cfaf50d9    repeat
2ae6a57dcdd2f1424598fc480cbf698a    repeat
0a5df23b922b9998bb7378f1ac03c98a    repeat
0a609db8d244100909a15d65eadf8539    repeat
0a61b571f594b6919601bcf3380da7f7    repeat
8bab3162259edfaadd1ea2e1fe7f58dc    repeat
4badd97df3e4ad6d64508b5c25d4dca9    repeat
Name: order_id, dtype: str

In [174]:
customer_sales_analysis=pd.DataFrame({
    'sales':customer_sales,
    'customer_type':customer_type
})

In [175]:
customer_sales_analysis

                                    sales customer_type
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2   129.90      one_time
0000b849f77a49e4a4ce2b2a4ca5be3f    18.90      one_time
0000f46a3911fa3c0805444483337064    69.00      one_time
0000f6ccb0745a6a4b88665a16c9f078    25.99      one_time
0004aac84e0df4da2b147fca70cf8255   180.00      one_time
...                                   ...           ...
fffcf5a5ff07b0908bd4e2dbc735a684  1570.00      one_time
fffea47cd6d3cc0a88bd621562a9d061    64.89      one_time
ffff371b4d645b6ecea244b27531430a    89.90      one_time
ffff5962728ec6157033ef9805bacc48   115.00      one_time
ffffd2657e2aad2907e67c3e9daecbeb    56.99      one_time

[95420 rows x 2 columns]

In [176]:
customer_sales_by_type_analysis=(customer_sales_analysis.groupby('customer_type')['sales'].sum())

In [177]:
customer_sales_by_type_analysis

customer_type
one_time    12828351.84
repeat        763291.86
Name: sales, dtype: float64

In [178]:
customer_sales_by_type_analysis_percentage=(customer_sales_by_type_analysis/customer_sales_by_type_analysis.sum())*100

In [179]:
customer_sales_by_type_analysis_percentage

customer_type
one_time    94.384109
repeat       5.615891
Name: sales, dtype: float64

In [181]:
df_main.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english', 'actual_delivery_days', 'delay_days',
       'delivery_status', 'order_month'],
      dtype='str')

In [210]:
total_sellers=df_main['seller_id'].nunique()

In [211]:
total_sellers

3095

In [212]:
sellers_sales=(df_main.groupby('seller_id')['price'].sum().sort_values(ascending=False))

In [213]:
sellers_sales.head(10)

seller_id
4869f7a5dfa277a7dca6462dcf3b52b2    229472.63
53243585a1d6dc2643021fd1853d8905    222776.05
4a3ca9315b744ce9f8e9374361493884    200472.92
fa1c13f2614d7b5c4749cbc52fecda94    194042.03
7c67e1448b00f6e969d365cea6b010ab    187923.89
7e93a43ef30c4f03f38b393420bc753a    176431.87
da8622b14eb17ae2831f4ac5b9dab84a    160236.57
7a67c85e85bb2ce8582c35f2203ad736    141745.53
1025f0e2d44d7041d6cf58b6550e0bfa    138968.55
955fee9216a65b617aa5c0531780ce60    135171.70
Name: price, dtype: float64

In [214]:
sellers_order=(df_main.groupby('seller_id')['order_id'].nunique())

In [215]:
sellers_order.sort_index().head(10)

seller_id
0015a82c2db000af6aaaf3ae2ecb0532      3
001cca7ae9ae17fb1caed9dfb1094831    200
001e6ad469a905060d959994f1b41e4f      1
002100f778ceb8431b7a1020ff7ab48f     51
003554e2dce176b5555353e4f3555ac8      1
004c9cd9d87a3c30c522c48c4fc07416    158
00720abe85ba0859807595bbf045a33b     13
00ab3eff1b5192e5f1a63bcecfee11c8      1
00d8b143d12632bad99c0ad66ad52825      1
00ee68308b45bc5e2660cd833c3f81cc    135
Name: order_id, dtype: int64

In [216]:
sellers_order.sort_values(ascending=False).head(20)

seller_id
6560211a19b47992c3666cc44a7e94c0    1854
4a3ca9315b744ce9f8e9374361493884    1806
cc419e0650a3c5ba77189a1882b7556a    1706
1f50f920176fa81dab994f9023523100    1404
da8622b14eb17ae2831f4ac5b9dab84a    1314
955fee9216a65b617aa5c0531780ce60    1287
7a67c85e85bb2ce8582c35f2203ad736    1160
ea8482cd71df3c1969d7b9473ff13abc    1146
4869f7a5dfa277a7dca6462dcf3b52b2    1132
3d871de0142ce09b7081e2b9d1733cb1    1080
7c67e1448b00f6e969d365cea6b010ab     982
8b321bb669392f5163d04c59e235e066     943
1025f0e2d44d7041d6cf58b6550e0bfa     915
620c87c171fb2a6dd6e8bb4dec959fc6     740
a1043bafd471dff536d0c462352beb48     718
cca3071e3e9bb7d12640c9fbe2301306     712
f8db351d8c4c4c22c6835c19a46f01b0     667
e9779976487b77c6d4ac45f75ec7afe9     657
fa1c13f2614d7b5c4749cbc52fecda94     585
7d13fca15225358621be4086e1eb0964     565
Name: order_id, dtype: int64

In [217]:
sellers_sales_average=(sellers_sales/sellers_order)

In [218]:
sellers_sales_average.sort_values(ascending=False).head(20)

seller_id
80ceebb4ee9b31afb6c6a916a574a1e2    6729.000000
ee27a8f15b1dded4d213a468ba4eb391    6499.000000
b37c4c02bda3161a7546a4e6d222d5b2    6018.750000
585175ec331ea177fa47199e39a6170a    3549.000000
abe021b01ba992245271b9aa422032df    3360.000000
a00824eb9093d40e589b940ec45c4eb0    3133.323333
e2a1ac9bf33e5549a2a4f834e70df2f8    2999.890000
e908c0f3646e8b60375734a350d95d71    2951.000000
d63c73efd41eb002280e7ec831424edb    2799.000000
1444c08e64d55fb3c25f0f09c07ffcf2    2749.000000
039e6ad9dae79614493083e241147386    2585.000000
961dff0a659b4561334372337dd897d9    2486.500000
c004e5ea15737026cecaee0447e00b75    2350.000000
6fa9202c10491e472dffd59a3e82b2a3    2338.080000
e3b4998c7a498169dc7bce44e6bb6277    2299.300000
8de8fe3af4449ed695d2434c933ed73e    2090.000000
2a167ca73899c85001a837d8fb4962f6    2048.500000
59417c56835dd8e2e72f91f809cd4092    2025.500000
8ec76bb0965af3f007692b26fa9d6623    1999.000000
bede56095ba33c42038fb85f707b8a42    1986.950000
dtype: float64

In [221]:
seller_aov=(
    sellers_sales[sellers_order>=50]/
    sellers_order[sellers_order>=50]
)

In [222]:
seller_aov.sort_values(ascending=False).head(10)

seller_id
e882b2a25a10b9c057cc49695f222c19    895.746316
17f51e7198701186712e53a39c564617    857.482143
966cb4760537b1404caedd472cc610a5    683.814000
04308b1ee57b6625f47df1d56f00eedf    639.687234
53243585a1d6dc2643021fd1853d8905    622.279469
834f3294fba9f932f56edc879193f925    604.659091
7681ef142fd2c19048da7430856b5588    541.386610
eeb6de78f79159600292e314a77cbd18    526.986024
7e93a43ef30c4f03f38b393420bc753a    525.094851
712e6ed8aa4aa1fa65dab41fed5737e4    503.987342
dtype: float64

In [229]:
total_product=df_main['product_id'].nunique()
total_product

32951

In [226]:
product_order=(df_main.groupby('product_id')['order_id'].nunique()).sort_values(ascending=False)

In [227]:
product_order.head(10)

product_id
99a4788cb24856965c36a24e339b6058    467
aca2eb7d00ea1a7b8ebd4e68314663af    431
422879e10f46682990de24d770e7f83d    352
d1c427060a0f73f6b889a5c7c61f2ac4    323
389d119b48cf3043d311335e499d9c6b    311
53b36df67ebb7c41585e8d54d6772e08    306
368c6c730842d78016ad823897a372db    291
53759a2ecddad2bb87a079a1f1519f73    287
154e7e31ebfa092203795c972e5804a6    269
2b4609f8948be18874494203496bc318    259
Name: order_id, dtype: int64

In [234]:
product_sales=(df_main.groupby('product_id')['price'].sum()).sort_values(ascending=False)
product_sales.head(10)

product_id
bb50f2e236e5eea0100680137654686c    63885.00
6cdd53843498f92890544667809f1595    54730.20
d6160fb7873f184099d9bc95e30376af    48899.34
d1c427060a0f73f6b889a5c7c61f2ac4    47214.51
99a4788cb24856965c36a24e339b6058    43025.56
3dd2a17168ec895c781a9191c1e95ad7    41082.60
25c38557cf793876c5abdd5931f922db    38907.32
5f504b3a1c75b73d6151be81eb05bdc9    37733.90
53b36df67ebb7c41585e8d54d6772e08    37683.42
aca2eb7d00ea1a7b8ebd4e68314663af    37608.90
Name: price, dtype: float64

In [235]:
product_sales_aov=product_sales/product_order

In [237]:
product_sales_aov.sort_values(ascending=False).head(10)

product_id
5769ef0a239114ac3a854af00df129e4    13440.00
489ae2aa008f021502940f251d4cce7f     6735.00
69c590f7ffc7bf8db97190b6cb6ed62e     6729.00
1bdf5e6731585cf01aa8169c7028d6ad     6499.00
c183fd5d2abf05873fa6e1014ed9e06c     5934.60
19936fa4f614ee0590d3b77ac83fd648     5230.00
a6492cc69376c469ab6f61d8f44de961     4799.00
c3ed642d592594bb648ff4a04cee2747     4690.00
259037a6a41845e455183f89c5035f18     4590.00
a1beef8f3992dbd4cd8726796aa69c53     4399.87
dtype: float64

In [241]:
product_sales_aov=(
    product_sales[product_order>=20]/
    product_order[product_order>=20]
).sort_values(ascending=False)
product_sales_aov.head(10)

product_id
d6160fb7873f184099d9bc95e30376af    1397.124000
25c38557cf793876c5abdd5931f922db    1023.876842
fb01a5fc09b9b9563c2ee41a22f07d54     697.157917
a04087ab6a96ffa041f8a2701a72b616     686.304348
f819f0c84a64f02d3a5606ca95edd272     644.988444
5f504b3a1c75b73d6151be81eb05bdc9     598.950794
1a080577618e7fe4d9ddd8fb2b47a964     570.717500
1dec4c88c685d5a07bf01dcb0f8bf9f8     570.428571
af0a99476d96dcc1a1baa7c0d9ff6b9d     538.195455
13db47eae724e2848e12b71a617a3a41     499.717308
dtype: float64

In [253]:
category_compair=pd.concat([category_sales,category_order],axis=1)
category_compair.columns=['total_sales','total_orders']

In [255]:
category_compair.sort_values('total_sales',ascending=False).head(10)

                               total_sales  total_orders
product_category_name_english
health_beauty                   1258681.34          8836
watches_gifts                   1205005.68          5624
bed_bath_table                  1036988.68          9417
sports_leisure                   988048.97          7720
computers_accessories            911954.32          6689
furniture_decor                  729762.49          6449
cool_stuff                       635290.85          3632
housewares                       632248.66          5884
auto                             592720.11          3897
garden_tools                     485256.46          3518

In [254]:
category_compair.sort_values('total_orders',ascending=False).head(10)

                               total_sales  total_orders
product_category_name_english
bed_bath_table                  1036988.68          9417
health_beauty                   1258681.34          8836
sports_leisure                   988048.97          7720
computers_accessories            911954.32          6689
furniture_decor                  729762.49          6449
housewares                       632248.66          5884
watches_gifts                   1205005.68          5624
telephony                        323667.53          4199
auto                             592720.11          3897
toys                             483946.60          3886

In [251]:
category_compair['aov']=(category_compair['total_sales']/category_compair['total_orders'])

In [252]:
category_compair.sort_values('aov',ascending=False).head(10)

                                       total_sales  total_orders          aov
product_category_name_english
computers                                222963.13           181  1231.840497
small_appliances_home_oven_and_coffee     47445.71            75   632.609467
home_appliances_2                        113317.74           234   484.263846
agro_industry_and_commerce                72530.47           182   398.519066
musical_instruments                      191498.88           628   304.934522
small_appliances                         190648.58           630   302.616794
fixed_telephony                           59583.00           217   274.576037
construction_tools_safety                 40544.52           167   242.781557
air_conditioning                          55024.96           253   217.489960
office_furniture                         273960.70          1273   215.208720

In [256]:
df_main[['product_id','product_category_name_english']].head(10)

                         product_id product_category_name_english
0  87285b34884572647811a353c7ac498a                    housewares
1  595fac2a385ac33a80bd5114aec74eb8                     perfumery
2  aa4383b373c6aca5d8797843e5594415                          auto
3  d0b61bfb1de832b15ba9d266ca96e5b0                      pet_shop
4  65266b2da20d04dbe00c5c2d3bb7859e                    stationery
5  060cb19345d90064d1015407193c233d                          auto
6  a1804276d9941ac0733cfd409f5206eb                       unknown
7  4520766ec412348b8d4caa5e8a18c464                          auto
8  ac1789e492dcd698c5c10b97a671243a               furniture_decor
9  9a78fb9862b10749a117f7fc3c31f051              office_furniture

In [258]:
top_product_sales=product_sales.head(10).reset_index()
top_product_sales=top_product_sales.merge(
    df_main[['product_id','product_category_name_english']].drop_duplicates('product_id'),on='product_id',how='left'
)
top_product_sales

                         product_id     price product_category_name_english
0  bb50f2e236e5eea0100680137654686c  63885.00                 health_beauty
1  6cdd53843498f92890544667809f1595  54730.20                 health_beauty
2  d6160fb7873f184099d9bc95e30376af  48899.34                     computers
3  d1c427060a0f73f6b889a5c7c61f2ac4  47214.51         computers_accessories
4  99a4788cb24856965c36a24e339b6058  43025.56                bed_bath_table
5  3dd2a17168ec895c781a9191c1e95ad7  41082.60         computers_accessories
6  25c38557cf793876c5abdd5931f922db  38907.32                          baby
7  5f504b3a1c75b73d6151be81eb05bdc9  37733.90                    cool_stuff
8  53b36df67ebb7c41585e8d54d6772e08  37683.42                 watches_gifts
9  aca2eb7d00ea1a7b8ebd4e68314663af  37608.90               furniture_decor

In [259]:
top_product_order=product_order.head(10).reset_index()

In [261]:
top_product_order=top_product_order.merge(
    df_main[['product_id','product_category_name_english']].drop_duplicates('product_id'),on='product_id',how='left'
)
top_product_order

                         product_id  order_id product_category_name_english
0  99a4788cb24856965c36a24e339b6058       467                bed_bath_table
1  aca2eb7d00ea1a7b8ebd4e68314663af       431               furniture_decor
2  422879e10f46682990de24d770e7f83d       352                  garden_tools
3  d1c427060a0f73f6b889a5c7c61f2ac4       323         computers_accessories
4  389d119b48cf3043d311335e499d9c6b       311                  garden_tools
5  53b36df67ebb7c41585e8d54d6772e08       306                 watches_gifts
6  368c6c730842d78016ad823897a372db       291                  garden_tools
7  53759a2ecddad2bb87a079a1f1519f73       287                  garden_tools
8  154e7e31ebfa092203795c972e5804a6       269                 health_beauty
9  2b4609f8948be18874494203496bc318       259                 health_beauty

In [262]:
df5.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [263]:
review_score_count=df5['review_score'].value_counts().sort_index()
review_score_count

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [265]:
average_review_score=df5['review_score'].mean()

In [266]:
average_review_score

np.float64(4.08642062404257)

In [267]:
df5['review_score'].isna().sum()

np.int64(0)

In [269]:
df_main.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name_english', 'actual_delivery_days', 'delay_days',
       'delivery_status', 'order_month'],
      dtype='str')

In [273]:
order_sales=(df_main.groupby('order_id')['price'].sum())

In [274]:
order_sales.head(10)

order_id
00010242fe8c5a6d1ba2dd792cb16214     58.90
00018f77f2f0320c557190d7a144bdd3    239.90
000229ec398224ef6ca0657da4fc703e    199.00
00024acbcdf0a6daa1e931b038114c75     12.99
00042b26cf59d7ce69dfabb4e55b4fd9    199.90
00048cc3ae777c65dbb7d2a0634bc1ea     21.90
00054e8431b9d7675808bcb819fb4a32     19.90
000576fe39319847cbb9d288c5617fa6    810.00
0005a1a1728c9d785b8e2b08b904576c    145.95
0005f50442cb953dcd1d21e1fb923495     53.99
Name: price, dtype: float64

In [277]:
review_sales=df5[['order_id','review_score']].merge(order_sales.rename('total_sales'),on='order_id',how='left')

In [280]:
review_sales.head()

                           order_id  review_score  total_sales
0  73fc7af87114b39712e6da79b0a377eb             4       370.00
1  a548910a1c6147796b98fdf73dbeba33             5        79.79
2  f9e4b658b201a9f2ecdecbb34bed034b             5       149.00
3  658677c97b385a9be170737859d3511b             5       179.99
4  8e6bfb81e283fa7e4f11123a3fb894f1             5      1199.00

In [281]:
sales_by_review=(review_sales.groupby('review_score')['total_sales'].sum()).sort_index()
sales_by_review

review_score
1    1812828.22
2     448799.56
3    1037092.59
4    2528015.01
5    7700489.39
Name: total_sales, dtype: float64

In [283]:
order_by_review=(review_sales.groupby('review_score')['order_id'].nunique()).sort_index()
order_by_review

review_score
1    11393
2     3148
3     8160
4    19098
5    57076
Name: order_id, dtype: int64

In [286]:
review_sales_aov=(sales_by_review/order_by_review)

In [287]:
review_sales_aov

review_score
1    159.117723
2    142.566569
3    127.094680
4    132.370668
5    134.916417
dtype: float64

In [291]:
sales_percentage_by_review=(sales_by_review/sales_by_review.sum())*100

In [292]:
sales_percentage_by_review

review_score
1    13.401331
2     3.317750
3     7.666706
4    18.688349
5    56.925863
Name: total_sales, dtype: float64

In [293]:
df_main.info()

<class 'pandas.DataFrame'>
Index: 112650 entries, 0 to 113424
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   customer_id                    112650 non-null  str
 2   order_status                   112650 non-null  str
 3   order_purchase_timestamp       112650 non-null  datetime64[us]
 4   order_approved_at              112635 non-null  datetime64[us]
 5   order_delivered_carrier_date   111456 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  112650 non-null  datetime64[us]
 8   order_item_id                  112650 non-null  float64
 9   product_id                     112650 non-null  str
 10  seller_id                      112650 non-null  str
 11  shipping_limit_date            112650 non-null  datetime64[us]
 12  price                          112650 non-null  float64
 13  freight_value                  112650 non-null  float64
 14  customer_unique_id             112650 non-null  str
 15  customer_zip_code_prefix       112650 non-null  int64
 16  customer_city                  112650 non-null  str
 17  customer_state                 112650 non-null  str
 18  product_category_name          112650 non-null  str
 19  product_name_lenght            112650 non-null  float64
 20  product_description_lenght     112650 non-null  float64
 21  product_photos_qty             112650 non-null  float64
 22  product_weight_g               112650 non-null  float64
 23  product_length_cm              112650 non-null  float64
 24  product_height_cm              112650 non-null  float64
 25  product_width_cm               112650 non-null  float64
 26  seller_zip_code_prefix         112650 non-null  float64
 27  seller_city                    112650 non-null  str
 28  seller_state                   112650 non-null  str
 29  product_category_name_english  112650 non-null  str
 30  actual_delivery_days           110196 non-null  float64
 31  delay_days                     110196 non-null  float64
 32  delivery_status                112650 non-null  str
 33  order_month                    112650 non-null  period[M]
dtypes: datetime64[us](6), float64(13), int64(1), period[M](1), str(13)
memory usage: 30.1 MB

In [295]:
df_main.shape

(112650, 34)

In [296]:
df_main.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
product_category_name               0
product_name_lenght                 0
product_description_lenght          0
product_photos_qty                  0
product_weight_g                    0
product_length_cm                   0
product_height_cm                   0
product_width_cm                    0
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
product_category_name_english       0
actual_delivery_days             2454
delay_days                       2454
delivery_status                     0
order_month                         0
dtype: int64

In [297]:
df_main.colums.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'seller_zip_code_prefix',
 'seller_city',
 'seller_state',
 'product_category_name_english',
 'actual_delivery_days',
 'delay_days',
 'delivery_status',
 'order_month']

In [298]:
df_main[['order_item_id','customer_zip_code_prefix','seller_zip_code_prefix']].head()

   order_item_id  customer_zip_code_prefix  seller_zip_code_prefix
0            1.0                      3149                  9350.0
1            1.0                     47813                 31570.0
2            1.0                     75265                 14840.0
3            1.0                     59296                 31842.0
4            1.0                      9195                  8752.0

In [299]:
df_main[['order_item_id','customer_zip_code_prefix','seller_zip_code_prefix']].dtypes

order_item_id               float64
customer_zip_code_prefix      int64
seller_zip_code_prefix      float64
dtype: object

In [300]:
df_main['order_item_id']=df_main['order_item_id'].astype('Int64')
df_main['seller_zip_code_prefix']=df_main['seller_zip_code_prefix'].astype('Int64')

In [301]:
df_main[['order_item_id','customer_zip_code_prefix','seller_zip_code_prefix']].dtypes

order_item_id               Int64
customer_zip_code_prefix    int64
seller_zip_code_prefix      Int64
dtype: object

In [302]:
df_main['order_month']=df_main['order_month'].dt.to_timestamp()

In [303]:
df_main['order_month'].head()

0   2017-10-01
1   2018-07-01
2   2018-08-01
3   2017-11-01
4   2018-02-01
Name: order_month, dtype: datetime64[us]

In [304]:
df_main['order_month'].dtype

dtype('<M8[us]')

In [305]:
df_main.shape

(112650, 34)

In [308]:
df_main.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
order_item_id                             Int64
product_id                                  str
seller_id                                   str
shipping_limit_date              datetime64[us]
price                                   float64
freight_value                           float64
customer_unique_id                          str
customer_zip_code_prefix                  int64
customer_city                               str
customer_state                              str
product_category_name                       str
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
seller_zip_code_prefix                    Int64
seller_city                                 str
seller_state                                str
product_category_name_english               str
actual_delivery_days                    float64
delay_days                              float64
delivery_status                             str
order_month                      datetime64[us]
dtype: object

In [309]:
df_main.duplicated().sum()

np.int64(0)

In [310]:
df_main['order_id'].nunique()

98666

In [311]:
df_main['seller_id'].nunique()

3095

In [312]:
df_main['product_id'].nunique()

32951

In [313]:
df_main['order_status'].value_counts()

order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

In [314]:
df_main['delivery_status'].value_counts()

delivery_status
early           101481
delay             7265
notdelivered      2454
ontime            1450
Name: count, dtype: int64

In [315]:
pd.crosstab(
    df_main['order_status'],
    df_main['delivery_status']
)

delivery_status  delay   early  notdelivered  ontime
order_status
approved             0       0             3       0
canceled             1       6           535       0
delivered         7264  101475             8    1450
invoiced             0       0           359       0
processing           0       0           357       0
shipped              0       0          1185       0
unavailable          0       0             7       0

In [316]:
df_main[
    (df_main['order_status'] == 'delivered') &
    (df_main['delivery_status'] == 'notdelivered')
][[
    'order_id',
    'order_status',
    'order_delivered_customer_date',
    'actual_delivery_days',
    'delay_days',
    'delivery_status'
]].head(20)

,order_id,order_status,order_delivered_customer_date,actual_delivery_days,delay_days,delivery_status
3376,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,NaT,NaN,NaN,notdelivered
23485,f5dd62b788049ad9fc0526e3ad11a097,delivered,NaT,NaN,NaN,notdelivered
49966,2ebdfc4f15f23b91474edf87475f108e,delivered,NaT,NaN,NaN,notdelivered
90294,e69f75a717d64fc5ecdfae42b2e8e086,delivered,NaT,NaN,NaN,notdelivered
94388,0d3268bad9b086af767785e3f0fc0133,delivered,NaT,NaN,NaN,notdelivered
105606,2d858f451373b04fb5c984a1cc2defaf,delivered,NaT,NaN,NaN,notdelivered
111339,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,NaT,NaN,NaN,notdelivered
111783,20edc82cf5400ce95e1afacc25798b31,delivered,NaT,NaN,NaN,notdelivered

In [317]:
df_main[
    (df_main['order_status'] == 'canceled') &
    (df_main['delivery_status'].isin(['early', 'delay']))
][[
    'order_id',
    'order_status',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'actual_delivery_days',
    'delay_days',
    'delivery_status'
]].head(20)

,order_id,order_status,order_delivered_customer_date,order_estimated_delivery_date,actual_delivery_days,delay_days,delivery_status
3284,1950d777989f6a877539f53795b4c3c3,canceled,2018-03-21 22:03:51,2018-03-09,30.093738,12.0,delay
9963,dabf2b0e35b423f94618bf965fcb7514,canceled,2016-10-16 14:36:59,2016-11-30,7.569525,-45.0,early
9964,dabf2b0e35b423f94618bf965fcb7514,canceled,2016-10-16 14:36:59,2016-11-30,7.569525,-45.0,early
66373,770d331c84e5b214bd9dc70a10b829d0,canceled,2016-10-14 15:07:11,2016-11-29,7.010197,-46.0,early
67569,8beb59392e21af5eb9547ae1a9938d06,canceled,2016-10-19 18:47:43,2016-11-30,10.937419,-42.0,early
105596,65d1e226dfaeb8cdc42f665422522d14,canceled,2016-11-08 10:58:34,2016-11-25,35.581169,-17.0,early
107662,2c45c33d2f9cb8ff8b1c86cc28c11c30,canceled,2016-11-09 14:53:50,2016-12-08,30.967986,-29.0,early

In [318]:
df_main.loc[
    df_main['order_status'] != 'delivered',
    'delivery_status'
] = 'notdelivered'

In [319]:
df_main['delivery_status'].value_counts()

delivery_status
early           101475
delay             7264
notdelivered      2461
ontime            1450
Name: count, dtype: int64

In [320]:
pd.crosstab(
    df_main['order_status'],
    df_main['delivery_status']
)

delivery_status  delay   early  notdelivered  ontime
order_status
approved             0       0             3       0
canceled             0       0           542       0
delivered         7264  101475             8    1450
invoiced             0       0           359       0
processing           0       0           357       0
shipped              0       0          1185       0
unavailable          0       0             7       0

In [321]:
df_main[['actual_delivery_days', 'delay_days']].describe()

       actual_delivery_days     delay_days
count         110196.000000  110196.000000
mean              12.472631     -12.030201
std                9.445655      10.160157
min                0.533414    -147.000000
25%                6.736262     -17.000000
50%               10.184282     -13.000000
75%               15.541097      -7.000000
max              209.628611     188.000000

In [322]:
df_main[df_main['order_status'] == 'delivered'][
    ['actual_delivery_days', 'delay_days']
].isna().sum()

actual_delivery_days    8
delay_days              8
dtype: int64

In [323]:
pd.crosstab(
    df_main['delivery_status'],
    pd.cut(
        df_main['delay_days'],
        bins=[-float('inf'), -0.0001, 0.0001, float('inf')],
        labels=['early', 'ontime', 'delay']
    )
)

delay_days        early  ontime  delay
delivery_status
delay                 0       0   7264
early            101475       0      0
notdelivered          6       0      1
ontime                0    1450      0

In [325]:
(df_main['price'] <= 0).sum()

np.int64(0)

In [326]:
df_main.to_csv('df_main_final.csv', index=False)

In [327]:
import os

os.path.exists('df_main_final.csv')

True